<?php

namespace MRBS\CalendarServer;

// An abstract interface with third-party Calendar services to achieve bidirectional data synchronization.
interface AbstractCalendarServerConnector {

  // Regularly pull update information from third-party Calendar services and synchronize it.
  // In the classic timed update design, the current status value will be sent to a third-party service,
  // and the third-party service will determine the create, update, and delete data
  // generated by the two synchronizations based on the status value.
  function pullCalendarUpdate();


  // Notify third-party services to create meetings.
  function createMeeting($entry);

  // Notify third-party services to decline meetings.
  function deleteMeeting($entry);

  // Notify third-party services to update meetings.
  function updateMeeting($entry);
}
