<?php

namespace MRBS\CalendarServer;

// An abstract interface with third-party Calendar services to achieve bidirectional data synchronization.
interface AbstractCalendarServerConnector {

  // Regularly pull update information from third-party Calendar services and synchronize it.
  // In the classic timed update design, the current status value will be sent to a third-party service,
  // and the third-party service will determine the create, update, and delete data
  // generated by the two synchronizations based on the status value.
  function pullCalendarUpdate();


  // Notify third-party service to create meetings.
  function createMeeting($entry);

  // Notify third-party service to decline meetings.
  function deleteMeeting($entry);

  // Notify third-party service to update meetings.
  function updateMeeting($entry);

  // Accept this meeting, which created from third-party service
  public function acceptMeeting($entry, string $msg);

  // Decline this meeting, which created from third-party service
  public function declineMeeting($entry, string $msg);

}
